name: sql_treino
description: A new Flutter project.

version: 1.1.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Basics
  cupertino_icons: ^1.0.3
  http: ^0.13.3
  curved_navigation_bar: ^1.0.3
  provider: ^6.0.3
  flutter_switch: ^0.3.2

  # Firebase
  firebase_core: ^2.4.0
  cloud_firestore: ^4.2.0
  firebase_storage: ^11.0.8
  image_picker: ^0.8.2

  # Local Storage
  shared_preferences: ^2.0.6

  # Workout Timer
  circular_countdown_timer: ^0.2.0
  flutter_tts: ^3.2.1

  # Calculadora
  function_tree: ^0.8.12

  # ChatApp
  flutter_typeahead: ^4.0.0

  # Somando Saber
  audioplayers: ^1.0.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  assets:
    - lib/assets/
    - lib/assets/Somando_Saber/
    - lib/assets/NavButton/
    - assets/

  uses-material-design: true
