name: sql_treino
description: A new Flutter project.

version: 1.1.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Basics
  cupertino_icons: ^1.0.3
  http: ^0.13.3
  
  # Firebase
  firebase_core: ^1.4.0
  cloud_firestore: ^2.4.0

  # Local Storage
  shared_preferences: ^2.0.6

  # Workout Timer
  circular_countdown_timer: ^0.2.0
  flutter_tts: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  assets:
    - lib/assets/
    - assets/

  uses-material-design: true
